version: "2"
services:
  elasticsearch:
    tty: true
    build: ./elasticsearch
    image: lbischof/elasticsearch
    ports:
      - "9200:9200"
  kibana:
    tty: true
    build: ./kibana
    image: lbischof/kibana
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
  logstash:
    tty: true
    build: ./logstash
    image: bobbydvo/ukc_logstash
    links:
      - "elasticsearch"
  filebeat:
    tty: true
    build: ./filebeat
    image: filebeat
    depends_on:
      - logstash
      - php-fpm
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
      - INDEX=logstash
    ports:
      - "80:80"
  php-fpm:
    tty: true
    image: bobbydvo/dummyapp_php-fpm:latest
    ports:
      - "9000:9000"
    environment:
      - APPLICATION_ENV=prod
  collectd:
    tty: true
    build: ./collectd
    image: bobbydvo/ukc_collectd
    depends_on:
      - logstash

